ALTER TABLE groups_users DROP CONSTRAINT FKgroups_use557639;
ALTER TABLE groups_users DROP CONSTRAINT FKgroups_use103015;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS groups_users CASCADE;
DROP TABLE IF EXISTS users CASCADE;

